# Use container-based infrastructure
sudo: false

language: scala

scala:
   - 2.12.3

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete > /dev/null
  - find $HOME/.sbt        -name "*.lock"               -print -delete > /dev/null

deploy:
  provider: script
  script: sbt ";generateCredential;set isSnapshot in ThisBuild := false;^ publish"
  on:
    all_branches: true
    tags: true
