addSbtPlugin("com.dwijnand" % "sbt-dynver" % "2.0.0")
//addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
//addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.8.5")
//addSbtPlugin("io.spray" % "sbt-revolver" % "0.8.0")
//addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.3")
//addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.5")
//addSbtPlugin("net.virtual-void" % "sbt-cross-building" % "0.8.1")